config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ideas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: %i[ show edit update destroy ]

  # GET /ideas or /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1 or /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas or /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully created." }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1 or /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully updated." }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1 or /ideas/1.json
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:name, :school, :picture, :pr, :reason)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :school, style: "display: block" %>
    <%= form.text_field :school %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture %>
  </div>

  <div>
    <%= form.label :pr, style: "display: block" %>
    <%= form.text_area :pr %>
  </div>

  <div>
    <%= form.label :reason, style: "display: block" %>
    <%= form.text_area :reason %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div id="<%= dom_id idea %>">

  <div id = "basic_info">
  <div id = "ns">
  <p class = "element">
    <strong>氏名<br></strong>
    <%= idea.name %>
  </p>

  <p class = "element">
    <strong>学校<br></strong>
    <%= idea.school %>
  </p>
  </div>

  <p class = "element">
    <%= image_tag(idea.picture_url , width:"600px") if idea.picture.present? %>
  </p>

  </div>

  <p class = "element">
    <strong>自己PR:</strong>
    <%= idea.pr %>
  </p>

  <p class = "element">
    <strong>志望理由:</strong>
    <%= idea.reason %>
  </p>

</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/index.html.erb
<body>
<header>
  <h1>JpbEntryMate</h1>
  <ul>
    <a href="introduction.html"><li><%= link_to "編集する", new_idea_path %></li></a>
    <a href="study.html"><li>削除する</li></a>
    <a href="dream.html"><li>ログアウト</li></a>
  </ul>
</header>

<main>

<div id="ideas">
  <% @ideas.each do |idea| %>
    <%= render idea %>

  <% end %>
</div>

</main>



</body>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/show.html.erb
<%= render @idea %>

<div>
  <%= link_to "Edit this idea", edit_idea_path(@idea) %> |
  <%= link_to "Back to ideas", ideas_path %>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobEntryMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class = "notice"><%= notice %></p>
    <p class = "alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>